### ISSUE TITLE
Error in connecting to moretube

### ISSUE THREAD

**Issue by indiasports** [MoarTube/MoarTube-Client#1]
<message: cleaning imported video directories, date: 2024-02-11 09:58:55>
<message: assessing system encoding/decoding capabilities, date: 2024-02-11 09:58:55>
<message: MoarTube Client is listening on port 8080, date: 2024-02-11 09:58:55>
<message: configured MoarTube Client with websocket server, date: 2024-02-11 09:58:55>
<message: CPU detected: Intel Core™ i7-10750H, date: 2024-02-11 09:58:58>
<message: GPU detected: NVIDIA GeForce RTX 3050 Laptop GPU, date: 2024-02-11 09:58:58>
<message: attempting user sign in with HTTP..., date: 2024-02-11 10:00:17>
<message: attempting user sign in with HTTPS..., date: 2024-02-11 10:00:38>
(node:4248) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
<message: none, date: 2024-02-11 10:00:59>
connect ETIMEDOUT 49.207.225.176:8080

Error: connect ETIMEDOUT 49.207.225.176:8080
    at AxiosError.from (C:\Windows\System32\MoarTube-Client\node_modules\axios\dist\node\axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (C:\Windows\System32\MoarTube-Client\node_modules\axios\dist\node\axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:518:28)
    at eventHandlers.<computed> (C:\Windows\System32\MoarTube-Client\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Error
    at C:\Windows\System32\MoarTube-Client\controllers\account.js:103:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cconley717** [comment]
It appears that you are attempting to sign into a node that is listening on port 8080 located at IP address 49.207.225.176, but the client is not able to find the node, leading to a connection reset. This is normal behavior in this circumstance.

MoarTube Node listens on port 80 by default; MoarTube Client listens on port 8080.

I have tried to ping 49.207.225.176; it is unreachable to me.

Please explain to me what you are trying to do and I will aid you further.
